services:
  mariadb:
    image: mariadb:11
    container_name: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: rootpass
      MARIADB_DATABASE: mi_base
      MARIADB_USER: userdao
      MARIADB_PASSWORD: userpass
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: mariadb
      PMA_USER: root
      PMA_PASSWORD: rootpass
    ports:
      - "8091:80"
    depends_on:
      - mariadb

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "StrongP@ssword123"
    ports:
      - "1433:1433"
    restart: always
    volumes:
      - sqlserver_data:/var/opt/mssql

volumes:
  mariadb_data:
  sqlserver_data: